### ISSUE TITLE
Encapsulated code

### ISSUE THREAD

**Issue by michielkouwenhoven** [malchata/yall.js#23]
It looks like there are three functions exposed to the global namespace (from the minified version).
Is it possible to encapsulate the code and only expose the 'yall' function to the global namespace?

Thanks

**Comment by malchata** [comment]
I certainly think so, and this was something I had been wondering about. I've gone ahead and implemented an encapsulation pattern to contain everything under `window.yall`. The only drawback is it requires instantiation of the object using the `new` keyboard, rather than a simple function call, but I think it's a reasonable tradeoff for keeping the `window` space a bit tidier.

**Comment by malchata** [comment]
Ha! Found a way to do it without introducing a breaking change. When I release the next version, this change will get out there. :)

Thanks for reporting!
