### ISSUE TITLE
Does it also work for IE10?

### ISSUE THREAD

**Issue by stratboy** [malchata/yall.js#27]
Hi, as per the title: does Yall also work for IE10?

**Comment by malchata** [comment]
Doubt it. I haven't tested, so I don't know for sure, but if it does work in IE10, it's entirely by accident.

**Comment by collinsethans** [comment]
Trying to understand: shouldn't it be working on older browsers, IE10 and other previous ones?

It says that whereever Intersection Observer is not available (including polyfill), it falls back to scroll/touch/orientation change -- so I tend to think that it will work on all older, just like the earlier packages, eg github.com/tuupola/jquery_lazyload.

I am new and exploring this package for possible production usage.

**Comment by stratboy** [comment]
> I am new and exploring this package for possible production usage.

Me too

**Comment by malchata** [comment]
After investigating, it appears yall.js does _not_ work for IE 10, mostly because it uses the `dataset` feature to manage `data-` attributes. I considered flipping these back to use `getAttribute`, but doing so would be a non-trivial change due to the script's current architecture.

Therefore, I will not be modifying this script to work with IE10, and to be fair, I had misgivings about doing so in the first place. IE10 represents, by _far_, a vast minority of browsers in use (0.1% globally according to caniuse.com). There may be some corporate intranets that still need to use it, but even so, I would have to think most of these organizations have updated to IE11, which yall.js supports.

I understand this might be disappointing, but I have to draw a line. To me, that line starts at IE10 (and earlier). I didn't make this decision lightly. Fortunately, there are a high number of IE10 compatible lazy loaders out there. [lazysizes](https://github.com/aFarkas/lazysizes) is one such option that works all the way back to IE8, even.

Closing for now.

**Comment by stratboy** [comment]
> I understand this might be disappointing

No you're not, no worry. It's true IE10 is not to be considered too much. I asked only because one of my clients still uses is, as you said, in his intranet. But I think I can use your script anyway someway.
Thank you for your code, regards.

**Comment by malchata** [comment]
So, somewhat opportunistically, the latest release of yall 2.2.1 now works in IE 10. I was able to remove use of the `dataset` feature. This doesn't mean IE10 is officially supported by IE 10, but I can verify that basic functionality works in this release through a Windows 7/IE 10 VM.

**Comment by stratboy** [comment]
Good to know, thank you :)

Jeremy Wagner ha scritto:
