### ISSUE TITLE
Missing files in the 3.1.5 npm install

### ISSUE THREAD

**Issue by Spomsoree** [malchata/yall.js#67]
I've noticed that some files are missing in the newest version (3.1.5).

https://registry.npmjs.org/yall-js

Here you can see that the newest version only contains 4 files, compared to the previous version with its 6 files.

Since the **.min.js** file is missing this might be a problem to some more people.

**Comment by malchata** [comment]
This was intentional so that the install footprint would be a bit lighter. The reasoning behind it is that `package.json` only points to `./src/yall.mjs` in the `module` and `jsnext:main` fields, and the `main` field points to the CommonJS version at `./dist/yall.js`.

Most people will consume yall as an npm package, and process the source with a bundler, and those who want to pluck the minified JS from the repo will probably do so on Github.

I can add these files back in for a future release, but I'm not necessarily convinced it's an issue. But I could be wrong. Let me know your thoughts.

**Comment by Spomsoree** [comment]
We install our packages via npm and concat them trough gulp to a single minified js file.

We can minify them ourself in this process, so this is not a real problem for us.

**Comment by dmnc** [comment]
This caught me out too. I was concatenating the yall.min.js directly.

I think the idea of optimising footprint is a noble one, but doing so in a patch version was definitely a surprise.

Given the yall.min.js is less than 2k, this might be trying to optimise a little too far? 😄

**Comment by dmnc** [comment]
What's more, this breaks ES5 using npm unless you are already running a transpiler.

When I discovered this problem I attempted to pull in the uncompressed version and uglify, but it is ES6 so uglify falls over. I think I'll have to downgrade for now.

**Comment by malchata** [comment]
Yeah, that's fair. I guess I didn't consider all the use cases around this, and just sort of assumed people `npm install` it and process their apps using a bundler.

I have a bug that I'm waiting on confirmation for in order to release 3.1.6. I'd be willing to add these files back in on that release.

I'm sorry for the pain this has caused.

**Comment by dmnc** [comment]
Thank you for such a quick response. I know how hard it can be to work out all your own use cases let alone those other people might come up with!
